---
- name: Config Backup (MikroTik RouterOS)
  routeros_command:
    commands: /export compact
  register: result

- name: Create a directory if it does not exist
  file:
    path: "{{ role_name }}/{{ group_names }}"
    state: directory

- copy:
    content: "{{ result.stdout.0[26:] }}"
    dest: "{{ role_name  }}/{{ group_names }}/{{ inventory_hostname }}.txt"
  with_items: "{{ group_names }}"
